GET http://localhost:3000/users
###

POST http://localhost:3000/register
Content-Type:application/json

{
    "name":"Jocelyn",
    "last_name":"Granger",
    "email": "mail@mwqdrwevr.com",
    "password": "crackmafasrcqcrtxertqwtvin"
}
###

POST http://localhost:3000/users/login
Content-Type:application/json

{
    "name":"Jocelyn",
    "password": "crackmafawtvin"
}